In [1]:
dataset_name = 'zw'

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score

In [3]:
def load_predictions(dataset_name):
    path = './Save Predict and Proba/' + dataset_name.upper() + '/pred_val_' + dataset_name.lower() + '.csv'
    table_pred = pd.read_csv(path)
    if dataset_name == 'zw':
        label = table_pred['norm']
        methods = table_pred.drop('norm', axis=1)
    else: 
        label = table_pred['class']
        methods = table_pred.drop('class', axis=1)
    methods = methods.drop('Unnamed: 0', axis=1)
    return label, methods

In [4]:
label, methods = load_predictions(dataset_name)

In [5]:
def get_oracle(labels, pred={}, clfs=[]):
    cont = 0;
    list_yes = np.zeros((len(labels)))
    oracle_preds = np.zeros((len(labels)))
    for i, k in enumerate(labels):
        acertou = False
        for clf in clfs:
            if pred[clf][i] == k:
                acertou = True
                oracle_preds[i] = pred[clf][i]
                break
        if acertou:
            cont += 1
            list_yes[i] = k
        else:
            oracle_preds[i] = pred[clf][0]
            if k == 0:
                list_yes[i] = 1
            else:
                list_yes[i] = 0
    return cont, list_yes, oracle_preds

In [6]:
clfs = ['SVM-CV', 'SVM-TFIDF', 'SVM-W2V', 'SVM-GLOVE', 'SVM-FAST', 'KNN-CV', 'KNN-TFIDF',
        'KNN-W2V', 'KNN-GLOVE', 'KNN-FAST', ]
names = {}
names['td'] = ['MLP-FAST','KNN-GLOVE','KNN-FAST','KNN-CV','MLP-W2V','NB-CV','CNN-TFIDF',
               'NB-FAST','RF-CV','LR-CV','CNN-CV','KNN-W2V', 'CNN-GLOVE']

names['zw'] = ['CNN-W2V', 'MLP-CV', 'SVM-TFIDF','KNN-GLOVE','LR-FAST','MLP-GLOVE',
               'SVM-CV','CNN-CV','KNN-CV', 'MLP-FAST','RF-W2V','CNN-FAST', 'RF-FAST']

names['td_zw'] = ['EXTRA-CV','CNN-FAST','MLP-W2V','LR-CV','MLP-FAST','NB-CV','CNN-CV',
                  'LR-GLOVE','SVM-GLOVE','RF-FAST','RF-TFIDF','SVM-CV', 'KNN-CV']

oracle, df_yes, oracle_preds = get_oracle(label.to_numpy(), methods, names[dataset_name])
print(oracle)

2644

# ORacle groups B

In [10]:
names = {}
names['fast'] = ['MLP-FAST','CNN-FAST','KNN-FAST','EXTRA-FAST','RF-FAST','SVM-FAST','LR-FAST','NB-FAST']
names['glove'] = ['MLP-GLOVE','CNN-GLOVE','KNN-GLOVE','EXTRA-GLOVE','RF-GLOVE','SVM-GLOVE','LR-GLOVE','NB-GLOVE']
names['cv'] = ['MLP-CV','CNN-CV','KNN-CV','EXTRA-CV','RF-CV','SVM-CV','LR-CV','NB-CV']
names['tfidf'] = ['MLP-TFIDF','CNN-TFIDF','KNN-TFIDF','EXTRA-TFIDF','RF-TFIDF','SVM-TFIDF','LR-TFIDF','NB-TFIDF']
names['w2v'] = ['MLP-W2V','CNN-W2V','KNN-W2V','EXTRA-W2V','RF-W2V','SVM-W2V','LR-W2V','NB-W2V']
                
for name in ['fast', 'glove', 'cv', 'tfidf', 'w2v']:
    oracle, df_yes, oracle_preds = get_oracle(label.to_numpy(), methods, names[name])
    print(f"{name}: {oracle}")
    score = f1_score(label.to_numpy(), oracle_preds, average='macro')
    print(f"{name} f1score: {score}")

fast: 2630
fast f1score: 0.9263733557596355
glove: 2568
glove f1score: 0.8868575291763102
cv: 2613
cv f1score: 0.9169661664177623
tfidf: 2609
tfidf f1score: 0.9122364655070632
w2v: 2648
w2v f1score: 0.9392753652170045

In [14]:
methods

,SVM-CV,SVM-TFIDF,SVM-W2V,SVM-GLOVE,SVM-FAST,LR-CV,LR-TFIDF,LR-W2V,LR-GLOVE,LR-FAST,...,KNN-CV,KNN-TFIDF,KNN-W2V,KNN-GLOVE,KNN-FAST,CNN-CV,CNN-TFIDF,CNN-W2V,CNN-GLOVE,CNN-FAST
0,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,1,2,2,2,2,2
1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3,2,2,2,2,2,2,2,2,2,2,...,2,2,1,2,2,2,2,2,2,2
4,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,1,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2785,2,2,2,2,2,2,2,2,2,2,...,2,2,2,1,2,2,2,2,2,2
2786,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2787,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2788,2,1,2,2,2,2,1,1,2,2,...,2,1,2,1,2,2,2,2,2,2
2789,2,2,2,2,2,2,2,2,2,2,...,2,2,1,0,0,2,2,2,2,2

In [16]:
from sklearn.preprocessing import Normalizer

In [17]:
norm = Normalizer()
from sklearn.datasets import make_classification
X, y = make_classification()
X_norm = norm.fit_transform(X)

In [18]:
X_norm

array([[ 0.28275515, -0.51154749, -0.0790374 , ..., -0.05188082,
        -0.10933351, -0.42855081],
       [-0.00567988, -0.13596537, -0.06206394, ..., -0.23053562,
        -0.21317666,  0.22147356],
       [ 0.09078263,  0.08784487, -0.26858697, ..., -0.05512732,
        -0.13362393, -0.14546904],
       ...,
       [-0.03478292,  0.06469125, -0.07604906, ...,  0.56736991,
        -0.06166445, -0.18015922],
       [-0.05348193, -0.04535214, -0.310444  , ..., -0.06061711,
         0.12219857, -0.13245229],
       [-0.02552117,  0.14884174,  0.11426646, ...,  0.05620241,
         0.13266982, -0.05554618]])